name: 'release'
on: # rebuild any PRs and main branch changes
  release:
    types: [created]
jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checking out!
        uses: actions/checkout@v3

      - name: Publish action package
        uses: ./
        with:
          force-publish-private-repo: true
          username: ${{ github.actor }}
          password: ${{ secrets.TEST_TOKEN_2 }}

      - name: Archive tarball
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: tarball
          path: /tmp/archive.tar.gz

      - name: Archive bundle
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: bundle.sigstore
          path: /tmp/bundle.sigstore

      - name: Archive zipfile
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: zip
          path: /tmp/archive.zip

      - name: annotations
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: zip
          path: /tmp/annotations.json
