name: 'release'
on: # rebuild any PRs and main branch changes
  release:
    types: [created]
jobs:
  package-and-publish: 
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: read
    steps:
      - name: Checking out!
        uses: actions/checkout@v3
        
      - name: Publish action package
        uses: ./
        with:
          force-publish-private-repo: true
      
      - name: Archive tarball
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: tarball
          path: /tmp/archive.tar.gz

      - name: Archive bundle
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: bundle.sigstore
          path: /tmp/bundle.sigstore